setting:
  binWidth: 128
  label: 1
  interpolator: 'sitkBSpline' 
  resampledPixelSpacing: [1, 1]
  weightingNorm: 


imageType:
  Original: {} #

featureClass:
  shape: []
  firstorder: [] 
  glcm: []
  glszm: []
  glrlm: []
  gldm: []
